# Generated by Django 4.2.1 on 2023-05-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='TaskState',
        ),
    ]
