# Generated by Django 4.2.1 on 2023-05-18 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_taskstatus_taskstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventtask',
            options={'verbose_name': 'Задача мероприятия', 'verbose_name_plural': 'Задачи мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='eventtaskreport',
            options={'verbose_name': 'Отчет о задаче мероприятия', 'verbose_name_plural': 'Отчеты о задачах мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='eventuser',
            options={'verbose_name': 'Участник мероприятия', 'verbose_name_plural': 'Участники мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='taskstate',
            options={'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник мероприятия'),
        ),
    ]
