# Generated by Django 4.2.1 on 2023-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtask',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
